name: axcend
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - aiohttp=3.7.4
  - aioredis=1.3.1
  - cerberus=1.3.4
  - dask=2022.2.0
  - nvidia::cudatoolkit=10.2
  - cudnn=8.2.0
  - h5py=2.10.0
  - numpy=1.19.2
  - pip>=20.2.4
  - python=3.8.5
  - pytorch::pytorch=1.8.0
  - pyyaml=5.3.1
  - scikit-image=0.17.2
  - scipy=1.5.2
  - pytorch::torchvision=0.9.0
  - zarr=2.11.0
  - pip:
    - connected-components-3d
    - pillow==8.3.1
    - ray[tune]==1.2.0
    - tensorflow==2.4.1
    - vedo==2022.0.1

