dataset:
    name: H5Dataset
    path: "./data/PVGPe"
    checkpoint_path: "./path_dataset_checkpoint"
    dataset_name_raw: data
    dataset_name_truth: truth
    crop_size: [64, 128, 128]
    augmentation: True
    include_centerline: False
    add_channel: True
    soft_labels: False
    resolution: [2., 0.578, 0.578]
model:
    name: AuxiliaryUNet3D
    pretrained_path: weights/pretrain_path/best.ckpt
    in_channels: 2
    out_channels: 1
    out_channels_aux: 1
    input_size: [64, 128, 128]
    num_levels: 4
    f_maps: 32
experiment:
    name: path
    trainer: PathTrainer
    metric: validation_loss
    mode: min
    num_epochs: 500
    steps_per_epoch: 8
    patience: 20
    microbatch_size: 8
    minibatch_sizes: [16]
    learning_rates: [0.00001]
    weight_decays: [0.001]
    loss:
        name: BCEWithLogitsLoss
