dataset:
    name: SliceDataset
    path: "./data/PVGPe"
    dataset_name_raw: data
    crop_size: [64, 128, 128]
    axis: 0
    num_permutations: 8
    slice_size: 8
    augmentation: True
    include_centerline: False
model:
    name: AuxiliaryUNet3D
    in_channels: 1
    out_channels: 1
    out_channels_aux: 8
    input_size: [64, 128, 128]
    num_levels: 4
    f_maps: 32
experiment:
    name: slice
    trainer: SliceTrainer
    metric: validation_loss
    mode: min
    num_epochs: 500
    steps_per_epoch: 32
    patience: 32
    microbatch_size: 8
    minibatch_sizes: [16]
    learning_rates: [0.001, 0.0001]
    weight_decays: [0.01, 0.001]
    loss:
        name: CrossEntropyLoss
